### ISSUE TITLE
No way to find things I've upvoted

### ISSUE THREAD

**Issue by andrew-vant** [ForumMagnum/ForumMagnum#1071]
Less Wrong Classic had an option in your profile that would show you all posts/comments you'd upvoted. I can't find any equivalent in the LW2 interface, and would like one. It's a convenient way to refresh old insights.

┆Issue is synchronized with this [Trello card](https://trello.com/c/d1VcelBu) by [Unito](https://www.unito.io/learn-more)

**Comment by tdnzr** [comment]
The [vote history](https://www.lesswrong.com/bookmarks#votehistory) is now available in the [bookmarks page](https://www.lesswrong.com/bookmarks), so this issue can be closed.
