### ISSUE TITLE
Think through where RSS source information is displayed

### ISSUE THREAD

**Issue by Discordius** [ForumMagnum/ForumMagnum#200]
The frontpage right now shows each post that is crossposted from a blog with the full nickname of that blog in smaller writing. That info is somewhat redundant to the author's name, and so I feel like I don't want to show it on the frontpage, but only show it on the actual posts page. 

@Raemon: any thoughts?

┆Issue is synchronized with this [Trello card](https://trello.com/c/8no5NME0) by [Unito](https://www.unito.io/learn-more)

**Comment by Discordius** [comment]
Discussion with Rob Bensinger on the topic: 

I wouldn't particularly object to SSC being mentioned somewhere on 

https://www.lesserwrong.com/posts/EctieqKwDQcQHhqZy/different-worlds

yeah

I just think it should be someplace minor

also I expect people to often manually cross-post stuff for whatever reason

and it would be nice if I can manually list the source for a thing, and have it show up the same as 
the auto-generated thing

maybe even with an optional 'date' field for when I'm cross-posting a thing EY posted to FB four 
years ago

**Comment by jimrandomh** [comment]
Currently when a post is auto-crossposted via RSS, it's displayed in `PostsItem` but not on `PostsPage`. This is approximately backwards; it should definitely appear on `PostsPage`, but might not be important enough to put in `PostsItem`.

(Also, it should be clickable.)

**Comment by jimrandomh** [comment]
See also #181.

**Comment by tdnzr** [comment]
Is this issue resolved via the implementation of crosspost phrasing? Like the phrasing "Crossposted from Don't Worry About the Vase" in this [Zvi post?](https://www.lesswrong.com/posts/kLa3HmkesF5w3MFEY/ai-26-fine-tuning-time)

**Comment by s-cheng** [comment]
@tdnzr Yup it seems like it's resolved
