### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by Discordius** [ForumMagnum/ForumMagnum#229]
Probably better to have an OK one now than a very good one later. Logo changes appear to be quite common.

┆Issue is synchronized with this [Trello card](https://trello.com/c/RyCMGZhP) by [Unito](https://www.unito.io/learn-more)

**Comment by zuuritaly** [comment]
Hello @Discordius  ,
I'm a graphic designer and I design logos for open source projects.

Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur
