### ISSUE TITLE
SequencesGrid should probably use grid instead of flexbox

### ISSUE THREAD

**Issue by s-cheng** [ForumMagnum/ForumMagnum#4921]
When there are exactly two sequences in a row, they are too spaced out:

![Screen Shot 2022-05-13 at 4 11 29 PM](https://user-images.githubusercontent.com/9057804/168374260-2d1aaa05-560c-4c5c-a271-98df0b64c15c.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1202276772599830) by [Unito](https://www.unito.io)

**Comment by Brandon-Perry** [comment]
@s-cheng @jpaddison3 is the intended behavior that they're right next to each other? Are there any figma or design docs I can look at?
