### ISSUE TITLE
[Rumor] "Report user" button sometimes doesn't work

### ISSUE THREAD

**Issue by s-cheng** [ForumMagnum/ForumMagnum#5056]
From a user via [Intercom](https://app.intercom.com/a/apps/xycbzvda/inbox/inbox/5179263/conversations/69456500015268):

> On Google Chrome, when I clicked on "report user" on the user's page nothing happened (no additional window opening in the page, no pop-up etc.).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1202452619489432) by [Unito](https://www.unito.io)

**Comment by aidan-fitz** [comment]
I've had this issue as well.

**Comment by darkruby501** [comment]
I think I was just passing along a user report too, didn't check myself, sorry.

**Comment by s-cheng** [comment]
fixed in https://github.com/ForumMagnum/ForumMagnum/pull/5433
