### ISSUE TITLE
closeDialog broken (breaks "Confirm" button in ckEditor collab post sharing settings, shortform dialog, maybe others)

### ISSUE THREAD

**Issue by darkruby501** [ForumMagnum/ForumMagnum#5477]
A recent change made by  breaks the “Confirm” button in ckEditor collaborative sharing settings popup and I think other modal dialogs too.

Specifically, adding the line
```(typeof componentProps.onClose === 'function') && componentProps.onClose()```
at line 28 in withDialog.tsx breaks it
Commit: https://github.com/ForumMagnum/ForumMagnum/pull/5433/commits/a33b666672504182c8af997b66d52f2b5c38afa6

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1202832741569839) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment]
Fixed by: https://github.com/ForumMagnum/ForumMagnum/pull/5478
