### ISSUE TITLE
Confusing UX for RSVP functionality on Events pages

### ISSUE THREAD

**Issue by SokolskyNikita** [ForumMagnum/ForumMagnum#5555]
The RSVP section on LW events looks like this:

![](https://user-images.githubusercontent.com/1880652/186984108-f0cf560c-69b2-4a8d-a6f5-09cd6947085b.png)

This is confusing because it _looks_ like clicking on the Going button should filter the attendees list to those who are "Going", but actually clicking it adds you to the RSVP list. I propose changing the buttons to something like this:

![](https://user-images.githubusercontent.com/1880652/186984741-0d9d4a7a-8f2e-4029-af73-0699ef3d259d.png)

The changes would be:

1. Add an `:` after `The host has requested RSVPs for this event` to hint at looking at the buttons to the right
1. Make the buttons look like they produce an action rather than filter the list below
1. Make the buttons more noticeable on the page
1. Change "Going" to "I'm going" to make it clear this is an action the user can take

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1202872293421154) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment]
We could try changing the buttons to the version that has a bounding box, but not a fill?

**Comment by jpaddison3** [comment]
I believe this is closed by: https://github.com/ForumMagnum/ForumMagnum/pull/5561
