### ISSUE TITLE
Readme or package.json have wrong instruction for local development

### ISSUE THREAD

**Issue by Huge** [ForumMagnum/ForumMagnum#5570]
If you run any of the 2 commands in https://github.com/ForumMagnum/ForumMagnum/tree/master#start-the-development-server , you do not get a server running, because in the implementation (in package.json) of the commands there are hardcoded paths like `../ForumCredentials/settings-dev.json`. Could this be mitigated?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1202881550422280) by [Unito](https://www.unito.io)

**Comment by brunoparga** [comment]
FWIW, I got a server running and the app seems fine. It is obviously missing things like the Algolia API key and the entire database of posts/etc, but it does sound I got farther than you did.

**Comment by jpaddison3** [comment]
`ea-start` is only for people with access to those secrets, `start` should work the way @brunoparga describes. I've updated the readme.
