### ISSUE TITLE
Event start-times and end-times should be typable

### ISSUE THREAD

**Issue by Raemon** [ForumMagnum/ForumMagnum#573]
Right now they're fairly annoying to edit – they require you to click up/down arrows, and once you've entered it if you want to edit it you have to go back into the widget.

If you attempt to type into the string field that's left after the widget closes, the entire string field disappears.

Possible solutions include replacing the widget, and/or making it so that you can edit the date-time string after it gets created by the widget. I think the second of those is more important.

┆Issue is synchronized with this [Trello card](https://trello.com/c/bZkCDmOC) by [Unito](https://www.unito.io/learn-more)

**Comment by Seanny123** [comment]
This seems to have been resolved in #4686
