### ISSUE TITLE
Hosted version?

### ISSUE THREAD

**Issue by rufuspollock** [ForumMagnum/ForumMagnum#6301]
Hi, i think this is a beautiful piece of forum software and would like to run a forum based on it. However, i don't want to have to do the hosting etc myself and wondered if you provided a SaaS service or knew of anyone who did? 

(Does the team behind this does host this for the EA and lesswrong forums?)

Thank-you for your efforts making this!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1203557692338331) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment]
Hello. Thanks for the kind words. There are two teams behind this repo: the LessWrong team, and the EA Forum team. We host the sites ourselves. We can't offer hosting sorry.

**Comment by rufuspollock** [comment]
Wondered whether there might be any shift in this policy - or at least some more installation instructions in the README to support others to install and run this.

Asking as we would love to run https://forum.secondrenaissance.net/ on this ...
