### ISSUE TITLE
Degraded perfomance in Firefox.

### ISSUE THREAD

**Issue by NunoSempere** [ForumMagnum/ForumMagnum#6628]
![de](https://user-images.githubusercontent.com/16527456/216199959-e92957ca-a325-4219-b684-5b6fc52a9a4e.png)

Issued highlighted in red.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1203880606070629) by [Unito](https://www.unito.io)

**Comment by NunoSempere** [comment]
I see, yes, I was viewing it with 150% zoom. With 100% zoom, it looks more similar to your screenshot:

![Screenshot from 2023-02-02 14-30-36](https://user-images.githubusercontent.com/16527456/216338161-0f9f3ca3-0b8b-4110-a962-69be0e9af9bf.png)

But it's too small for normal reading.

**Comment by jpaddison3** [comment]
I too am a fan of increasing the font size on many websites. However once we're talking about at 3% market-share browser at nonstandard font-size, it does start to get hard to make an impact case for prioritization. In any case though, I _still_ cannot reproduce:

<img width="2988" alt="image" src="https://user-images.githubusercontent.com/10352319/216347292-f5740e2a-7755-4312-8cd3-62d6fa7d11d1.png">

**Comment by NunoSempere** [comment]
Turns out you were right, I had some weird Firefox settings (in particular, zoom was only applying to the text). Thanks!
