### ISSUE TITLE
Comments broken on the EA Forum

### ISSUE THREAD

**Issue by NunoSempere** [ForumMagnum/ForumMagnum#6679]
- Description: When loading a post, comments simply don't show up.
- Expected behavior: Comments do show up
- Testing done: Tested on Firefox/Chrome/custom Webkit browser, on Linux.
- 
![forum-no-comments](https://user-images.githubusercontent.com/16527456/218455005-a2c4609a-f741-4cc6-99d4-970021d57041.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1203958047618269) by [Unito](https://www.unito.io)

**Comment by oetherington** [comment]
@NunoSempere Thanks for the bug report! This issue should now be fixed.
