### ISSUE TITLE
EA forum "customize feed" on desktop double-toggling

### ISSUE THREAD

**Issue by edoarad** [ForumMagnum/ForumMagnum#6833]
Every second expansion of "customize feed" leads to an automatic collapse of the topics section on desktop (and not on mobile)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1204236503731637) by [Unito](https://www.unito.io)

**Comment by s-cheng** [comment]
@edoarad Thanks for reporting this! We just deployed the [fix](https://github.com/ForumMagnum/ForumMagnum/pull/6836)
