### ISSUE TITLE
Error in estimating reading time

### ISSUE THREAD

**Issue by edoarad** [ForumMagnum/ForumMagnum#6880]
https://forum.effectivealtruism.org/users/katja_grace
![image](https://user-images.githubusercontent.com/24963373/229308134-51baa34a-dbe5-49c2-853e-cdeb4c68698f.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1204313988493896) by [Unito](https://www.unito.io)

**Comment by edoarad** [comment]
Also, [Jeff](https://forum.effectivealtruism.org/users/jeff_kaufman)'s. I guess this is probably a Markdown thing?

**Comment by jimrandomh** [comment]
I believe the issue specifically affects posts using the ForumMagnum crossposting feature, where the primary version of the post is on the other end of the crosspost.

**Comment by jpaddison3** [comment]
Jim is correct. Long term, this will be fixed by fully denormalizing post contents across Forums. Short term, this should be solved by hiding reading times for crossposts.
