### ISSUE TITLE
bug in redirecting URL automatically generated from linkpost

### ISSUE THREAD

**Issue by edoarad** [ForumMagnum/ForumMagnum#6982]
[This post](https://forum.effectivealtruism.org/posts/Erw9x4i9Tkcyb32oA/who-were-the-righteous-among-the-nations)  has the following linkpost: 
```[yadvashem.org/righteous/about-the-righteous.html](https://forum.effectivealtruism.org/out?url=yadvashem.org%2Frighteous%2Fabout-the-righteous.html)```

But the redirect doesn't seem to work.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1204426034069496) by [Unito](https://www.unito.io)

**Comment by Will-Howard** [comment]
This is fixed now, it was just missing the `https://` from the url
