### ISSUE TITLE
feature suggestion - autoupdated google doc <-> post integration

### ISSUE THREAD

**Issue by edoarad** [ForumMagnum/ForumMagnum#7279]
Many people prefer to edit in google docs, especially for the collaborative features.

Copy-pasting from google docs works great, except in cases where the google doc is continuously updated. 

One possible integration could maybe like this:
Sharing the google doc with a designated LW/AF/EAF account, with comment permissions. 
When creating a post, linkpost to the google doc, where an option to connect the post with the doc is available. 
If selected, the post will be posted (using the copy-paste mechanism).
In the backend, we check for updates every 1h. If there's a new update, and it is older than 1h, update the post accordingly.
Also, comments from the forum can be transferred to the google doc simply.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1204695149256081) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment]
See: https://github.com/ForumMagnum/ForumMagnum/issues/7232

**Comment by jpaddison3** [comment]
I think I will prefer to track this inside the existing issue. (No worries about the dup Edo)
