### ISSUE TITLE
TypeError: e.coauthors is null in Recent Discussion

### ISSUE THREAD

**Issue by sduncan01** [ForumMagnum/ForumMagnum#7320]
I see an error reading
Error: TypeError: e.coauthors is null
in the Recent Discussion feed on the 
LessWrong front page. Currently (11:45 pm Eastern time on June 3) this error appears between sections for [this post](https://www.lesswrong.com/posts/vnJ5grhqhBmPTQCQh/boundaries-part-2-trends-in-ea-s-handling-of-boundaries) and [this post](https://www.lesswrong.com/posts/B7duehMp2mSvffu2T/ai-14-a-very-good-sentence). Screenshot:

![Screenshot_20230603_233654_Firefox](https://github.com/ForumMagnum/ForumMagnum/assets/14204397/f516da93-d5f9-4151-8a81-3a95c79fbf30)

This is on Firefox for Android, and I see it whether or not I select the "Desktop mode" browser option. I assume it's due to some sort of bug; there's a small chance I will try to look into the details when I'm on my laptop, but I am going ahead and reporting it now, from my phone, as I don't really expect to get around to that soon.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1204751450696311) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment]
This was a an issue with a deploy which has since been fixed.
