### ISSUE TITLE
Q&A Focus mode doesn't hide the entire page

### ISSUE THREAD

**Issue by tdnzr** [ForumMagnum/ForumMagnum#7697]
There's a "Focus mode" button in the "New Answer / New Comment" field on Q&A posts ([example link](https://www.lesswrong.com/posts/PKw5h7aeHNywirJoi/would-you-pay-for-a-search-engine-limited-to-rationalist)).

a) The button only makes the screen white, instead of truly hiding it, so you still have to scroll past the various white sections.
b) If you scroll down far enough, not all the comments/answers are hidden.
c) Maybe b) is caused by the fact that this (or all?) Q&A page(s) have excess whitespace at the bottom? See [this screenshot](https://i.imgur.com/9XBrppn.png) of the same post.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1205251618458558) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment]
I can't repro problem (a), exactly. I agree it's pretty low down on my screen, but if you're clicking the button, you must have already scrolled to it?

**Comment by michaelkeenan** [comment]
This should be fixed now—tdnzr, does it seem better to you?

**Comment by tdnzr** [comment]
Yup, the main issue with the Q&A focus mode toggle seems to be fixed. The Q&A post still has excess whitespace, but I've spun that off into a separate issue, #7888.
