### ISSUE TITLE
Vote history page - anchor links are broken

### ISSUE THREAD

**Issue by tdnzr** [ForumMagnum/ForumMagnum#7698]
In the [Vote History](https://www.lesswrong.com/bookmarks#votehistory) page, the comment anchor link is broken: the date is displayed correctly, but instead of linking to the actual comment, the link just points to the LW homepage.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1205251000347568) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment]
This problem affects both LW and the EA Forum
