### ISSUE TITLE
Vote History page - missing context menu options

### ISSUE THREAD

**Issue by tdnzr** [ForumMagnum/ForumMagnum#7699]
On a typical post, the comment menu (vertical ellipsis in the top right) for my own comment has 6 options, but in the [Vote History](https://www.lesswrong.com/bookmarks#votehistory) page, the options "Pin to my profile", "Report" (why can I report my own comment, anyway?_?), and "Delete" are missing.

Conversely, for comments by other users, in the Vote History, the "Report" button is missing.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1205251342558118) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment]
Thanks for these bug reports. I am very confused what the bleep is going on here.
