### ISSUE TITLE
Vote History page suggestion - don't display own comments

### ISSUE THREAD

**Issue by tdnzr** [ForumMagnum/ForumMagnum#7700]
Because one's own comments are upvoted by default, the vote history contains all one's own comments, too.

a) That clutters the vote history.
b) It's redundant with one's [comment feed](https://www.lesswrong.com/users/mondsemmel/replies) linked from the [user page](https://www.lesswrong.com/users/mondsemmel).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1205251145488210) by [Unito](https://www.unito.io)

**Comment by tdnzr** [comment]
Is this change supposed to be live? In the [vote history](https://www.lesswrong.com/bookmarks#votehistory), I still see my own comments with my own default upvotes

**Comment by s-cheng** [comment]
It was fixed in https://github.com/ForumMagnum/ForumMagnum/pull/8267 and is currently deployed on the EA Forum. I think LW hasn't deployed the fix yet.
