### ISSUE TITLE
First-time commenter help link is broken

### ISSUE THREAD

**Issue by steve31415** [ForumMagnum/ForumMagnum#7849]
I am a new LessWrong user. I clicked the "Reply" link on a comment, and a dialog appeared with help material aimed at first-time commenters. However, the dialog contains a broken link, which presumably should be updated or removed.

Here are the contents of the dialog:

> LessWrong ain't your typical web forum
> 
> All first-time comments get reviewed by moderators to ensure they're productive contributions that fit with LessWrong's particular culture/values/goals. New users start our rate limited to 3 comments per day and one post per week (but you'll get more commenting privileges as you gain karma).
> 
> Learn more at:
> 
> - [New User's Guide](https://www.lesswrong.com/posts/LbbrnRvc9QwjJeics/new-user-s-guide-to-lesswrong)
> - [Four things to help your first submission be well-received](https://www.lesswrong.com/posts/7mMPvzoWvnDjC4Q6c/four-things-to-help-your-first-submission-be-well-received)

The second link leads to the following message:

> Sorry, you don't have access to this page. This is usually because the post in question has been removed by the author.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1205458512233023) by [Unito](https://www.unito.io)

**Comment by We13b-MD** [comment]
#7849 I will love to help but can you give me a guideline to start

**Comment by We13b-MD** [comment]
@steve31415  #7849 I will love to help can you give me guideline to start

**Comment by steve31415** [comment]
Are you looking for a guideline as to how to go about fixing this? I'm afraid I have no idea; I'm new to LessWrong and don't know anything about the codebase nor the content which that broken link was meant to lead to.

**Comment by We13b-MD** [comment]
Thanks a lot will figure it out

**Comment by jimrandomh** [comment]
The message is generated from a comment (with its ID in a server config setting); that comment is [this one](https://www.lesswrong.com/posts/zXJfH7oZ62Xojnrqs/lesswrong-moderation-messaging-container#QgwD7PkQHFp3nfhjj). The link to "Four things to help your first submission be well-received" was broken because that post is a draft. Ruby has edited the comment to take out the broken link, so this should be fixed now.
