### ISSUE TITLE
link text is not being broken across lines

### ISSUE THREAD

**Issue by zackmdavis** [ForumMagnum/ForumMagnum#8053]
I'm seeing links not being broken across lines when that would be the sane text-wrapping behavior. Instead, the entire link appears on the next line. This is easier to explain with a screenshot:

![link_not_breaking](https://github.com/ForumMagnum/ForumMagnum/assets/1076988/6161f296-e4d3-4bd6-8186-7007075a70bd)

(Screenshot is from https://www.lesswrong.com/posts/4hLcbXaqudM9wSeor/philosophy-in-the-darkest-timeline-basics-of-the-evolution, but the behavior also seems to be exhibited in comments [(_e.g._)](https://www.lesswrong.com/posts/i5kijcjFJD6bn7dwq/evaluating-the-historical-value-misspecification-argument?commentId=Ga3uxkTamCfyJ78Qt#Ga3uxkTamCfyJ78Qt).)

This seems to be a recent regression. I'm using Firefox 118.0.1 on Xubuntu.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1205764316296925) by [Unito](https://www.unito.io)

**Comment by b0b3rt** [comment]
Fixed [here](https://github.com/ForumMagnum/ForumMagnum/pull/8049), deploy PR [here](https://github.com/ForumMagnum/ForumMagnum/pull/8054)

**Comment by b0b3rt** [comment]
Seems to be fixed now.
