### ISSUE TITLE
Probable bug with tag voting permissions

### ISSUE THREAD

**Issue by michaelkeenan** [ForumMagnum/ForumMagnum#8610]
Looking into a puzzling thing at Waking Up, I came across what I'm pretty sure is a bug (though not one that affects Waking Up because we do tags differently). I'd investigate more thoroughly but I'm a bit pressed for time at the moment.

See the [commit 7500b0d](https://github.com/ForumMagnum/ForumMagnum/commit/7500b0d) from March 2023. The `canVoteOnTag` function in /lib/voting/tagRelVoteRules.tsx was changed from returning a boolean to returning an object that can be `{ fail: false }` or `{ fail: true, reason: string }`.

However, in the `shouldHideTagForVoting` function in /lib/collections/tags/permissions.ts, the `canVoteOnTag` function is used as if it still returns a boolean, like this: `!canVoteOnTag(tag?.canVoteOnRels, user, post, 'smallUpvote')`

So `shouldHideTagForVoting` must always return false, and so (I expect, though I haven't tested this) tags for voting are never hidden even in cases when they should be.

[I made a branch with what I think is the fix](https://github.com/ForumMagnum/ForumMagnum/commit/b8dfebbe235f50976c8ae4645f4c9842fd97bb11) and I considered making a PR, but I haven't actually tested it so that seems irresponsible.

Looks like @jpaddison3  and @oetherington worked on this code a while back, so I'll leave it to you from here.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1206291774403771) by [Unito](https://www.unito.io)

**Comment by b0b3rt** [comment]
Hm, seems like there should be a lint rule that checks whether we're checking the negated value of something that's never false-y (since that's nearly always going to be a bug like this).

**Comment by oetherington** [comment]
Your branch with the fix looks correct to me 👍
