### ISSUE TITLE
Integrate sentry for tracking of JavaScript errors

### ISSUE THREAD

**Issue by jglamine** [ForumMagnum/ForumMagnum#901]
Right now we have no way of knowing what JavaScript errors people are getting.

We should integrate Sentry (or a similar service) so that when JavaScript errors happen in people's browsers, we send the error to Sentry. This will allow us to notice and fix bugs.

They have a free version with 10k errors per month. We should start with that and if it seems useful we can upgrade to on of the paid plans. We can also configure it to only send like 10% of errors, which should save on pricing while still allowing us to see general trends.

https://sentry.io/

**Comment by Discordius** [comment]
This is related to our general logging setup, which I think can be greatly improved. We currently export our logs to Timber, but that doesn't cover client reporting. I looked into a few different services, but didn't find anything that seemed great. Interested in discussing this more.
